### PR TITLE
Add number of issuers to arguments of deserialize

### PR DESCRIPTION
**Pull request by djw8605**

### CODE REVIEW

**Comment by bbockelm** [comment]
Why this instead of the existing `nullptr`-terminated list?

**Comment by djw8605** [comment]
I think a nullptr terminated list is fine, just more difficult to use.  A small issue, gcc on rhel7 doesn't support the `nullptr` by default, but can with a gcc flag.

For example, if a user is reading in a list from a configuration file, they probably read it into a data structure like vector.  Then the arguments would be something like:
```
&issuers_vector[0], issuers_vector.size()
```
But, if you want to make it into a `nullptr` terminated list of strings, then you have to perform a few more steps.  Dynamically allocate the list of `char*`, then copy in the string contents...

**Comment by bbockelm** [comment]
If you're a C++ caller, you probably still have to do multiple allocations, no?  Not like you can simply give a reference to a `std::vector<std::string>` as this needs an array-of-pointers...

**Comment by djw8605** [comment]
indeed, my solution only works if it's a `std::vector<char*>`.

Yeah, multiple allocation are probably required no matter what.  But which is more "c"'ism?

**Comment by bbockelm** [comment]
I'd like to stick with the current interface as-is: I've seen C libraries use both styles here.

If necessary, we can get a few more data points and introduce a "v2" API as necessary.

**Pull request closed without merging**
