### PR TITLE
Fix FindUUID for macOS

### LINKED ISSUE #70: macOS build broken by 52b2210
The macOS builds were broken by 52b221014d19a8c9e3b583aa046f9a287fd49cba. The code that was removed should probably be reintroduced inside an `if(APPLE)` conditional.

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR fixes #70 by partially reverting 52b221014d19a8c9e3b583aa046f9a287fd49cba.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
Can this be merged?

**Comment by djw8605** [comment]
@duncanmmacleod do you need a release tagged for this?

**Comment by duncanmmacleod** [comment]
> @duncanmmacleod do you need a release tagged for this?

No.

**Comment by DrDaveD** [comment]
I would like a new tagged release so it will include #67 which was merged into the master branch last month.

**Pull request merged**
