### PR TITLE
Fixup WLCG compat for HTCondor READ

### PR DESCRIPTION
**Pull request by brianhlin**
Per @bbockelm

### CODE REVIEW

**Review by djw8605 — COMMENTED** [review]
Is this tested?  A few lines below at https://github.com/scitokens/scitokens-cpp/blob/7bf5fe428a17c7e0318d56223f6bfbbbee60be65/src/scitokens_internal.cpp#L627 

It uses `/WRITE` with the slash, which makes sense given it's a path.

**Comment by bbockelm** [comment]
Yeah, should be /READ

**Comment by brianhlin** [comment]
Ah, right. Fixed. This did however fix the issue I was having so maybe there's some path normalization occurring further down the line?

**Review by djw8605 — APPROVED** [review]
LGTM

**Pull request merged**
