### PR TITLE
CMake3 has a different package name on EL7

### PR DESCRIPTION
**Pull request by brianhlin**

### CODE REVIEW

**Review by djw8605 — COMMENTED** [review]
I'm surprised this is needed since it built just fine for epel 7.

**Comment by djw8605** [comment]
Since this package is targeted towards EPEL, I will keep it as is.

**Comment by brianhlin** [comment]
@djw8605 I could also add an `if %{?osg}` so that we don't have to worry about spec files diverging between EPEL/OSG. Would that work for you?

**Comment by djw8605** [comment]
Sure, that works for me.

**Pull request closed without merging**
